site_name: YOLOV - GPT adventure

nav:
  - index.md
  - Itinerary: hike.md
  - Gear: gear.md
  - Trail food: food.md
  - Contact: contact.md

theme:
  name: material

  features:
    - navigation.footer
    - navigation.instant
    - navigation.sections

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - glightbox

markdown_extensions:

  # Python Markdown
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - admonition
  - attr_list
