site_name: Our GPT Adventure

nav:
  - index.md
  - Planning & Logistics: logistics.md
  - Itinerary: hike.md
  - Gear: gear.md
  - Trail food: food.md
  - Joys & Pains: emotions.md
  - Contact: contact.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@DarkaMaul
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@cervenka_iris

copyright: Copyright &copy; 2023 - Alexis Challande & Iris Cervenka

theme:
  name: material

  features:
    - navigation.footer
    - navigation.instant
    - navigation.sections

  font:
    text: Raleway

  logo: assets/logo.png
  favicon: assets/favicon.ico

  palette:
    primary: blue grey

plugins:
  - search
  - glightbox:
      auto_caption: true

markdown_extensions:

  # Python Markdown
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # Others
  - tables
  - meta
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - abbr

extra_css:
  - stylesheets/extra.css

